import { mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { getProject } from "../project-store.js";
import { registerTool } from "../tool-registry.js";
const sandboxRoot = path.resolve(process.env.WEBNESTDEV_SANDBOX_DIR ?? ".webnestdev/sandboxes");
const rootFor = (id: string) => path.join(sandboxRoot, id);
function safePath(id: string, p: string) { const root = rootFor(id); const target = path.resolve(root, p || "."); if (target !== root && !target.startsWith(root + path.sep)) throw new Error("Path escapes project sandbox"); return target; }
async function requireProject(id: string) { if (!await getProject(id)) throw new Error("Project not found"); await mkdir(rootFor(id), { recursive: true }); }
registerTool({ name:"fs.list", description:"List files and directories. Input: {path?: string}.", async(input,c)=>{ await requireProject(c.projectId); const p=(input as {path?:string}).path??"."; return (await readdir(safePath(c.projectId,p),{withFileTypes:true})).map(e=>({name:e.name,type:e.isDirectory()?"directory":"file"})); }});
registerTool({ name:"fs.read", description:"Read a UTF-8 text file. Input: {path: string}.", async(input,c)=>{ await requireProject(c.projectId); const p=(input as {path?:string}).path; if(!p) throw new Error("path is required"); return {path:p,content:await readFile(safePath(c.projectId,p),"utf8")}; }});
registerTool({ name:"fs.write", description:"Create or replace a UTF-8 text file. Input: {path: string, content: string}.", async(input,c)=>{ await requireProject(c.projectId); const v=input as {path?:string;content?:string}; if(!v.path||typeof v.content!=="string") throw new Error("path and content are required"); const target=safePath(c.projectId,v.path); await mkdir(path.dirname(target),{recursive:true}); await writeFile(target,v.content,"utf8"); return {ok:true,path:v.path,bytes:Buffer.byteLength(v.content)}; }});
registerTool({ name:"fs.rename", description:"Rename a path inside the project. Input: {from: string, to: string}.", async(input,c)=>{ await requireProject(c.projectId); const v=input as {from?:string;to?:string}; if(!v.from||!v.to) throw new Error("from and to are required"); await mkdir(path.dirname(safePath(c.projectId,v.to)),{recursive:true}); await rename(safePath(c.projectId,v.from),safePath(c.projectId,v.to)); return {ok:true,from:v.from,to:v.to}; }});
registerTool({ name:"fs.delete", description:"Delete a path inside the project. Input: {path: string}.", async(input,c)=>{ await requireProject(c.projectId); const p=(input as {path?:string}).path; if(!p||p===".") throw new Error("Refusing to delete sandbox root"); await rm(safePath(c.projectId,p),{recursive:true,force:true}); return {ok:true,path:p}; }});